// Icon name → Lucide component mapping. The webmail uses a stable
// `<Icon name="...">` API so call sites don't bind to specific Lucide
// component names; this file is the single point where the icon set is
// defined. Adding a new icon = importing it from `@lucide/svelte` and
// dropping it in the map below.

import {
    Inbox, Star, FileEdit, Send, Trash2, ShieldAlert, Folder, Mail,
    Paperclip, Search, RefreshCw, Moon, Sun, Monitor, Sparkles, Wand2, Camera, EyeOff,
    Reply, Archive, FolderInput, X, ChevronLeft, ChevronRight, ChevronDown, ChevronUp, Plus,
    Download, Eye, User, LogOut, Info, Settings, CalendarDays,
    ShieldCheck, Filter, AtSign, Bell, Mic, Palette, Globe, Wifi, Copy,
    Check, Clock, KeyRound, Lock, HatGlasses, GripVertical, Type,
    HardDrive, LayoutGrid, List as ListIcon, FolderOpen, File, Image,
    FileText, Music, Video, Trash, Upload, MoreVertical,
    FileArchive, FileCode, FileSpreadsheet, FilePen, FileType, FileVideoCamera,
    FileAudio, FileImage, FileJson, FileTerminal, Presentation, Database, Table, BookText, Binary,
    CloudOff, WifiOff, AlertCircle, Bug, RotateCcw, FolderUp, Pencil, Link, Phone,
    Volume2, VolumeX, Ghost, ArrowUpDown,
    type Icon as LucideIcon
} from '@lucide/svelte';

// Internal name → Lucide component. Where the existing webmail used a
// "filled star" we render the same component with `fill="currentColor"`
// applied at the call site (see Icon.svelte).
export const ICONS = {
    inbox: Inbox,
    star: Star,
    starFilled: Star,        // rendered with fill in Icon.svelte
    drafts: FileEdit,
    sent: Send,
    trash: Trash2,
    spam: ShieldAlert,
    folder: Folder,
    mail: Mail,
    paperclip: Paperclip,
    search: Search,
    refresh: RefreshCw,
    moon: Moon,
    sun: Sun,
    monitor: Monitor,
    sparkles: Sparkles,
    wand: Wand2,
    send: Send,
    reply: Reply,
    archive: Archive,
    move: FolderInput,
    close: X,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    plus: Plus,
    download: Download,
    eye: Eye,
    user: User,
    logout: LogOut,
    info: Info,
    settings: Settings,
    calendar: CalendarDays,
    shield: ShieldCheck,
    filter: Filter,
    at: AtSign,
    bell: Bell,
    mic: Mic,
    palette: Palette,
    globe: Globe,
    wifi: Wifi,
    copy: Copy,
    check: Check,
    clock: Clock,
    key: KeyRound,
    lock: Lock,
    spy: HatGlasses,
    gripVertical: GripVertical,
    type: Type,
    pencil: Pencil,
    link: Link,
    drive: HardDrive,
    grid: LayoutGrid,
    listView: ListIcon,
    folderOpen: FolderOpen,
    file: File,
    image: Image,
    fileText: FileText,
    music: Music,
    video: Video,
    upload: Upload,
    moreVertical: MoreVertical,
    camera: Camera,
    eyeOff: EyeOff,
    fileArchive: FileArchive,
    fileCode: FileCode,
    fileSpreadsheet: FileSpreadsheet,
    filePen: FilePen,
    fileType: FileType,
    fileVideoCamera: FileVideoCamera,
    cloudOff: CloudOff,
    wifiOff: WifiOff,
    alertCircle: AlertCircle,
    shieldAlert: ShieldAlert,
    bug: Bug,
    refreshCw: RefreshCw,
    rotateCcw: RotateCcw,
    folderUp: FolderUp,
    fileAudio: FileAudio,
    fileImage: FileImage,
    fileJson: FileJson,
    fileTerminal: FileTerminal,
    presentation: Presentation,
    database: Database,
    table: Table,
    bookText: BookText,
    binary: Binary,
    phone: Phone,
    volume: Volume2,
    volumeOff: VolumeX,
    ghost: Ghost,
    arrowUpDown: ArrowUpDown
} satisfies Record<string, typeof LucideIcon>;

export type IconName = keyof typeof ICONS;
